apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecon-demo
  labels:
    app: kubecon-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecon-demo
  template:
    metadata:
      labels:
        app: kubecon-demo
    spec:
      containers:
      - name: kubecon-demo-ctr
        image: alena1108/kubecon:v0.7.0
        imagePullPolicy: Always
